export const Products = [
    {
      id: 1,
      category: 'shoe',
      name: 'Air Max 200',
      imageSrc: require('../images/sneekers.png'),
      price: '$ 250',
      rating: 5,
      discount: '8%',
      favourite: 'yes',
      size: ['US 6', 'US 7', 'US 8', 'US 9'],
      color: [['#FADF2B', '#F7F7D8'], ['#FF2C57', '#FADBDD'], ['#FF88DB', '#FBE7F3'], ['#7C8CFF', '#E3E8FA']],
    },
    {
      id: 2,
      category: 'backpack',
      name: 'Hiking Starlet',
      imageSrc: require('../images/backpack.png'),
      price: '$ 350',
      rating: 5,
      discount: '5%',
      favourite: 'yes',
      size: ['US 6', 'US 7', 'US 8', 'US 9'],
      color: [['#FADF2B', '#F7F7D8'], ['#FF2C57', '#FADBDD'], ['#FF88DB', '#FBE7F3'], ['#7C8CFF', '#E3E8FA']],
    },
    {
      id: 3,
      category: 'backpack',
      name: 'Hand Bag',
      imageSrc: require('../images/backpack02.png'),
      price: '$ 80',
      rating: 3.5,
      discount: '8%',
      favourite: 'no',
      size: ['US 6', 'US 7', 'US 8', 'US 9'],
      color: [['#FADF2B', '#F7F7D8'], ['#FF2C57', '#FADBDD'], ['#FF88DB', '#FBE7F3'], ['#7C8CFF', '#E3E8FA']],
    },
    {
      id: 4,
      category: 'shoe',
      name: 'Nike Air Max',
      imageSrc: require('../images/sneekers02.png'),
      price: '$ 240',
      rating: 4,
      discount: 'none',
      favourite: 'no',
      size: ['US 6', 'US 7', 'US 8', 'US 9'],
      color: [['#FADF2B', '#F7F7D8'], ['#FF2C57', '#FADBDD'], ['#FF88DB', '#FBE7F3'], ['#7C8CFF', '#E3E8FA']],
    },
    {
      id: 5,
      category: 'watch',
      name: 'Royal Rolex',
      imageSrc: require('../images/watch.png'),
      price: '$ 50',
      rating: 5,
      discount: 'none',
      favourite: 'no',
      size: ['US 6', 'US 7', 'US 8', 'US 9'],
      color: [['#FADF2B', '#F7F7D8'], ['#FF2C57', '#FADBDD'], ['#FF88DB', '#FBE7F3'], ['#7C8CFF', '#E3E8FA']],
    },
    {
      id: 6,
      category: 'shoe',
      name: 'Hiker Max',
      imageSrc: require('../images/sneekers03.png'),
      price: '$ 180',
      rating: 4.5,
      discount: 'none',
      favourite: 'no',
      size: ['US 6', 'US 7', 'US 8', 'US 9'],
      color: [['#FADF2B', '#F7F7D8'], ['#FF2C57', '#FADBDD'], ['#FF88DB', '#FBE7F3'], ['#7C8CFF', '#E3E8FA']],
    },
    {
      id: 7,
      category: 'backpack',
      name: 'School Bag',
      imageSrc: require('../images/backpack01.png'),
      price: '$ 120',
      rating: 3.5,
      discount: '10%',
      favourite: 'no',
      size: ['US 6', 'US 7', 'US 8', 'US 9'],
      color: [['#FADF2B', '#F7F7D8'], ['#FF2C57', '#FADBDD'], ['#FF88DB', '#FBE7F3'], ['#7C8CFF', '#E3E8FA']],
    },
    {
      id: 8,
      category: 'watch',
      name: 'Silver Liner',
      imageSrc: require('../images/watch01.png'),
      price: '$ 35',
      rating: 4.5,
      discount: '22%',
      favourite: 'yes',
      size: ['US 6', 'US 7', 'US 8', 'US 9'],
      color: [['#FADF2B', '#F7F7D8'], ['#FF2C57', '#FADBDD'], ['#FF88DB', '#FBE7F3'], ['#7C8CFF', '#E3E8FA']],
    },
    {
      id: 9,
      category: 'shoe',
      name: 'Leather Sneaker',
      imageSrc: require('../images/sneekers01.png'),
      price: '$ 200',
      rating: 4,
      discount: 'none',
      favourite: 'no',
      size: ['US 6', 'US 7', 'US 8', 'US 9'],
      color: [['#FADF2B', '#F7F7D8'], ['#FF2C57', '#FADBDD'], ['#FF88DB', '#FBE7F3'], ['#7C8CFF', '#E3E8FA']],
    },
  ];
  